services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  kafka:
    image: 'apache/kafka-native:4.0.0'
    ports:
      - '9092:9092'
      - '9093:9093'
      - '9094:9094'
      - '2181:2181'
